### ISSUE TITLE
[1.16.5] JEI compatibility was broken: "NoSuchMethodError: ..."

### ISSUE THREAD

**Issue by wasdspace** [Darkhax-Minecraft/Enchantment-Descriptions#125]
Forge: 36.2.35
JEI: 7.7.1.152
Bookshelf: 10.4.32
Enchantment Descriptions: 7.0.19

```
[Render thread/ERROR] [mezz.jei.gui.recipes.RecipeLayout/]: Error caught from Recipe Category: net.darkhax.enchdesc.jei.CategoryEnchantmentInfo
java.lang.NoSuchMethodError: mezz.jei.ingredients.IngredientManager.isIngredientVisible(Ljava/lang/Object;Lmezz/jei/ingredients/IngredientFilter;)Z
	at net.darkhax.enchdesc.jei.EnchantmentInfoEntry.lambda$getCompatibleItems$0(EnchantmentInfoEntry.java:93) ~[enchdesc:7.0.19]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at net.darkhax.enchdesc.jei.EnchantmentInfoEntry.getCompatibleItems(EnchantmentInfoEntry.java:93) ~[enchdesc:7.0.19]
	at net.darkhax.enchdesc.jei.CategoryEnchantmentInfo.setRecipe(CategoryEnchantmentInfo.java:81) ~[enchdesc:7.0.19]
	at net.darkhax.enchdesc.jei.CategoryEnchantmentInfo.setRecipe(CategoryEnchantmentInfo.java:24) ~[enchdesc:7.0.19]
	at mezz.jei.gui.recipes.RecipeLayout.create(RecipeLayout.java:72) ~[jei:7.7.1.152]
	at mezz.jei.gui.recipes.RecipeGuiLogic.getRecipeLayouts(RecipeGuiLogic.java:178) ~[jei:7.7.1.152]
	at mezz.jei.gui.recipes.RecipeGuiLogic.getRecipeLayouts(RecipeGuiLogic.java:164) ~[jei:7.7.1.152]
	at mezz.jei.gui.recipes.RecipesGui.updateLayout(RecipesGui.java:497) ~[jei:7.7.1.152]
	at mezz.jei.gui.recipes.RecipesGui.onStateChange(RecipesGui.java:549) ~[jei:7.7.1.152]
	at mezz.jei.gui.recipes.RecipeGuiLogic.setRecipeCategory(RecipeGuiLogic.java:201) ~[jei:7.7.1.152]
	at mezz.jei.gui.recipes.RecipeCategoryTab.handleClick(RecipeCategoryTab.java:44) ~[jei:7.7.1.152]
	at mezz.jei.input.CombinedMouseHandler.handleClickInternal(CombinedMouseHandler.java:95) ~[jei:7.7.1.152]
	at mezz.jei.input.CombinedMouseHandler.handleVanillaClick(CombinedMouseHandler.java:43) ~[jei:7.7.1.152]
	at mezz.jei.input.CombinedMouseHandler.handleClick(CombinedMouseHandler.java:27) ~[jei:7.7.1.152]
	at mezz.jei.gui.recipes.RecipesGui.func_231044_a_(RecipesGui.java:355) ~[jei:7.7.1.152]
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?]
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?]
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:181) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?]
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:180) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133) ~[fpsreducer:1.24-mc1.16.5]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:109) ~[?:?]
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:306) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:997) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-Forge_36.2.35.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.35.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
```
[debug.log](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/files/8933907/debug.log)
[latest.log](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/files/8933908/latest.log)

**Comment by Darkhax** [comment]
Thanks for letting me know, I am surprised nobody has mentioned this sooner. The issue has been fixed and an update has been published to CurseForge. Please update to 7.1.20.
