### ISSUE TITLE
"Mod enchdesc requires bookshelf 18 or above"

### ISSUE THREAD

**Issue by NidaimeHokage** [Darkhax-Minecraft/Enchantment-Descriptions#193]
A mod loading error has occurred to me after downloading the _EnchantmentDescriptions-Forge-1.19.4-15.0.1.jar_. 
I do not know, where to find/download the missing part "bookshelf 18". 
I know there are a few older closed cases facing the "booksheld issue" but it didn't really helped me until now.

Thanks for an answer :)

Some more information:

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:61) ~[forge-1.19.4-45.0.50-universal.jar%23173!/:?] {re:classloading}
-- MOD enchdesc --
Details:
	Mod File: /C:/Users/Nils/AppData/Roaming/.minecraft/mods/EnchantmentDescriptions-Forge-1.19.4-15.0.1.jar
	Failure message: Mod enchdesc requires bookshelf 18 or above
		Currently, bookshelf is not installed
	Mod Version: 15.0.1
	Mod Issue URL: https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/issues
	Exception message: MISSING EXCEPTION MESSAGE
Stacktrace:
	at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:61) ~[forge-1.19.4-45.0.50-universal.jar%23173!/:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:59) ~[forge-1.19.4-45.0.50-universal.jar%23173!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:165) ~[forge-1.19.4-45.0.50-universal.jar%23173!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:591) ~[client-1.19.4-20230314.122934-srg.jar%23168!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:582) ~[client-1.19.4-20230314.122934-srg.jar%23168!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:585) ~[client-1.19.4-20230314.122934-srg.jar%23168!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_86412_(LoadingOverlay.java:196) ~[client-1.19.4-20230314.122934-srg.jar%23168!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1363) ~[client-1.19.4-20230314.122934-srg.jar%23168!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1160) ~[client-1.19.4-20230314.122934-srg.jar%23168!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:731) ~[client-1.19.4-20230314.122934-srg.jar%23168!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[1.19.4-forge-45.0.50.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.4-45.0.50.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

**Comment by Darkhax** [comment]
You can download Bookshelf from CurseForge. It's linked on the file page where you should have downloaded this mod from. This is the exact file you want for Forge 1.19.4. https://www.curseforge.com/minecraft/mc-mods/bookshelf/files/4454755

**Comment by NidaimeHokage** [comment]
Thank you very much!
