### ISSUE TITLE
Missing dependency on Modrinth

### ISSUE THREAD

**Issue by Ghent** [Darkhax-Minecraft/Enchantment-Descriptions#217]
Hello,

Modrinth does not show the dependency on `bookshelf` and therefore fails during load after installation.

```Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install bookshelf, version 20 or later.
More details:
	 - Mod 'EnchantmentDescriptions' (enchdesc) 17.0.9 requires version 20 or later of bookshelf, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:194)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by Darkhax** [comment]
Thanks for letting me know, I've updated the most recent releases for each mc version to show bookshelf.
