### ISSUE TITLE
Client crash on startup Forge 1.16.4

### ISSUE THREAD

**Issue by khamseen** [Darkhax-Minecraft/Enchantment-Descriptions#41]
Hey, getting a crash when I add this mod to my mod folder. 
Running Forge 1.16.4-35.0.7
Mod version EnchantmentDescriptions-1.16.4-6.0.1
Crash happens at launch.

`[10Nov2020 00:16:19.015] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[10Nov2020 00:16:19.016] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[10Nov2020 00:16:19.016] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[10Nov2020 00:16:19.016] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[10Nov2020 00:16:19.017] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[10Nov2020 00:16:19.017] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[10Nov2020 00:16:19.017] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[10Nov2020 00:16:19.017] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10Nov2020 00:16:19.018] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10Nov2020 00:16:19.018] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10Nov2020 00:16:19.018] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10Nov2020 00:16:19.019] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[10Nov2020 00:16:19.019] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$376/1143390193.call(Unknown Source)
[10Nov2020 00:16:19.019] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[10Nov2020 00:16:19.019] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[10Nov2020 00:16:19.020] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.RuntimeException: java.lang.IllegalAccessError: tried to access field net.minecraft.util.ObjectIntIdentityMap.field_148749_a from class net.minecraftforge.registries.GameData$ClearableObjectIntIdentityMap
[10Nov2020 00:16:19.020] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:43)
[10Nov2020 00:16:19.020] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.main.Main.main(Main.java:123)
[10Nov2020 00:16:19.020] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	... 11 more
[10Nov2020 00:16:19.021] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.util.ObjectIntIdentityMap.field_148749_a from class net.minecraftforge.registries.GameData$ClearableObjectIntIdentityMap
[10Nov2020 00:16:19.021] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraftforge.registries.GameData$ClearableObjectIntIdentityMap.clear(GameData.java:407)
[10Nov2020 00:16:19.022] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraftforge.registries.GameData$BlockCallbacks.onClear(GameData.java:460)
[10Nov2020 00:16:19.022] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:538)
[10Nov2020 00:16:19.022] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:649)
[10Nov2020 00:16:19.022] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraftforge.registries.GameData.vanillaSnapshot(GameData.java:261)
[10Nov2020 00:16:19.023] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:51)
[10Nov2020 00:16:19.023] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123)
[10Nov2020 00:16:19.023] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.client.main.Main$$Lambda$489/1476235721.run(Unknown Source)
[10Nov2020 00:16:19.023] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[10Nov2020 00:16:19.024] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[10Nov2020 00:16:19.024] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[10Nov2020 00:16:19.024] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[10Nov2020 00:16:19.024] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.Thread.run(Thread.java:745)`

**Comment by Darkhax** [comment]
This issue is related to a race condition in Forge itself. They're looking into it, but it has nothing to do with this mod.

**Comment by khamseen** [comment]
Ah thanks for letting me know. Out of all my mods it was only happening when I had this one in which is why I came here. Will keep an eye out on the Forge updates.
